// <auto-generated />
using System;
using Hospitalpage.Infrastructure.Manager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospitalpage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240922110515_addboolss")]
    partial class addboolss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hospitalpage.Models.Appoinment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("A_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("A_Age");

                    b.Property<sbyte>("AppoinmentStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("A_AppoinmentStatus");

                    b.Property<DateTime>("AppoinmentTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("A_AppoinmentTime");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("A_DoctorName");

                    b.Property<double>("MobileNumber")
                        .HasColumnType("double")
                        .HasColumnName("A_MobileNumber");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("A_Sex");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("A_UserName");

                    b.HasKey("Id");

                    b.ToTable("Appoinments");
                });
#pragma warning restore 612, 618
        }
    }
}
